name: Go

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get dependencies for Linux
      run: sudo apt-get install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libgl1-mesa-dev xorg-dev

    - name: Get dependencies
      run: go get -v -t -d ./...

    # - name: Build
    #  run: go build -v ./...

    - name: Build for Win
      env:
        goos: windows
        goarch: amd64 
        run: |
           mkdir ./winapp
      　   go build -v -o ./winapp/app_win.exe ./...
          
          

